apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2026-02-21T23:41:52Z"
  generation: 1
  labels:
    app: microservice
  name: microservice
  namespace: validate
  resourceVersion: "549725"
  uid: eb91c695-5ad0-4ca1-8f5e-6e75ab29d789
spec:
  securityContext:
    runAsUser: 1000    # Reuire use to have this userID
            
  progressDeadlineSecond: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: microservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - image: docker.io/library/app
        imagePullPolicy: Always
        name: app
        resources: {}
        terminationMessagePath: /dev/termination-log
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true        
terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
